### ISSUE TITLE
Test only on Python changes to ameliorate Google geocoding billiing change

### ISSUE THREAD

**Issue by hcarter333** [hcarter333/rm-rbn-history#108]
Change the logging update action so that it only looks for locations of spotters when there are associated spots for on of the stations tracked  by the application.  

The tests of the code in the app are using 7 geocoding calls per action. Modify the action so that tests are only run if the Python files change.

**Comment by hcarter333** [comment]
Chat GPT says:

```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 1) Diff the push range and count how many .py files changed
      - name: Detect Python changes
        id: py_check
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
                   | grep -E '\.py$' || true)
          echo "count=$(echo \"$files\" | wc -l)" >> $GITHUB_OUTPUT

      # 2) Only run pytest if the count is non-zero
      - name: Run pytest
        if: ${{ steps.py_check.outputs.count != '0' }}
        run: |
          pytest --maxfail=1 --disable-warnings -q

```

Trying it now...
